#! /bin/sh

pomo() {
	zenity --info --text="Starting Pomodoro Timer!"
	sleep 1500 && zenity --info --text="Time to take a break?"
  sleep 300 && zenity --question --text="Back to work! Restart timer?" --ok-label="No." --cancel-label="Yes, restart!"
}

pomo
while [ $? -ne 0 ]; do pomo; done

